### ISSUE TITLE
cumngun

### ISSUE THREAD

**Issue by nerd137** [dleovl/test1#1]
### Device Model

iphone 3g, arm11

### iOS Version

17.0

### Bootstrap Version

4.5

### Serotonin Version

-

### What happened?

I tried to hack cumngun but now my phone bootloop 

### Log output

```shell
mobile@localhost:/$ sudo ./cumngun.sh
Removing 13984 Directories and Files recursively...
```

### Acknowledgement of README and FAQ

- [ ] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Discord: <https://discord.com/users/1068204818952364032>
Username Alias: GrassLOL
Reddit: u/error-the-reddit-boi

Watch your tone. I am stalking and I am lurking.
